apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  labels:
    app: product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      name: product-db
      labels:
        app: product-db
    spec:
      containers:
        - name: product-db
          envFrom:
            - configMapRef:
                name: product-service-cfg
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: product-db
spec:
  type: LoadBalancer
  selector:
    app: product-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
