apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-cfg
data:
  POSTGRES_DB: 'products'
  POSTGRES_URL: 'jdbc:postgresql://product-db:5432/products'
  POSTGRES_PASSWORD: 'postgres_password'
  POSTGRES_USER: 'postgres_user'

