spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/products}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

server:
  servlet:
    context-path: /product-service
